In [18]:
import pandas as pd
laptop = pd.read_csv('laptops.csv')
laptop["category"]="laptop"
laptop.head()

,id_product,name_product,description,category
0,asus-vivobook-go-15-e1504fa-r5-nj776w,Asus Vivobook Go 15 E1504FA R5 7520U (NJ776W),Laptop Asus Vivobook Go 15 E1504FA R5 7520U (N...,laptop
1,hp-15-fd0234tu-i5-9q969pa,HP 15 fd0234TU i5 1334U (9Q969PA),Tích hợp tuyệt vời với đa dạng chế độ làm việc...,laptop
2,dell-inspiron-15-3520-i5-n5i5057w1,Dell Inspiron 15 3520 i5 1235U (N5I5057W1),Laptop Dell Inspiron 15 3520 i5 1235U (N5I5057...,laptop
3,lenovo-ideapad-slim-3-15irh10-i5-83k1000hvn,Lenovo IdeaPad Slim 3 15IRH10 i5 13420H (83K10...,Laptop Lenovo IdeaPad Slim 3 15IRH10 i5 13420H...,laptop
4,macbook-air-13-inch-m4-16gb-256gb,MacBook Air 13 inch M4 16GB/256GB,"Không làm người dùng thất vọng, Apple đã cho r...",laptop

In [19]:
mobile = pd.read_csv('mobile.csv')
mobile["category"]="mobile"
mobile.head()

          id_product             name_product     description category
0  vivo-y19s-pro-8gb  vivo Y19s Pro 8GB/128GB  Không có mô tả   mobile
1          honor-400  HONOR 400 5G 12GB/256GB  Không có mô tả   mobile
2  oppo-a5x-4gb-64gb        OPPO A5x 4GB/64GB  Không có mô tả   mobile
3  iphone-16-pro-max  iPhone 16 Pro Max 256GB        Xem thêm   mobile
4      iphone-16-pro      iPhone 16 Pro 128GB        Xem thêm   mobile

In [20]:
camera = pd.read_csv('camera.csv')
camera["category"]="camera"
camera.head()

,id_product,name_product,description,category
0,camera-ip-360-do-2mp-tp-link-tapo-c200c,Camera IP 360 Độ 2MP TP-Link Tapo C200C,Bảo vệ ngôi nhà của bạn một cách toàn diện với...,camera
1,camera-ip-360-do-3mp-imou-ta32cp-l-trang,Camera IP 360 Độ 3MP IMOU TA32CP-L,Camera IP 360 Độ 3MP IMOU TA32CP-L là một sản ...,camera
2,camera-ip-360-do-1080p-ezviz-c6n-trang,Camera IP 360 Độ 2MP Ezviz C6N,Camera IP 360 Độ 2MP Ezviz C6N nổi bật với khả...,camera
3,camera-ip-360-do-2mp-tiandy-tc-h322n,Camera IP 360 Độ 2MP TIANDY TC-H322N,Camera IP 360 Độ 2MP TIANDY TC-H322N là một sả...,camera
4,camera-ip-360-do-3mp-ezviz-ty1,Camera IP 360 Độ 3MP EZVIZ TY1,Camera IP 360 Độ 3MP EZVIZ TY1 với khả năng qu...,camera

In [21]:
capsac = pd.read_csv('capsac.csv')
capsac["category"]="capsac"
capsac.head()

,id_product,name_product,description,category
0,cap-type-c-type-c-2m-xmobile-dr-t11?utm_flashs...,Cáp Type C - Type C 2m Xmobile DR-T11,Cáp Type C - Type C 2m Xmobile DR-T11 hỗ trợ s...,capsac
1,sac-xe-hoi-type-c-pd-30w-baseus-tiny-star-mini...,Sạc xe hơi Baseus VCHXXC,"Trong cuộc sống hiện đại, việc sở hữu một thiế...",capsac
2,adapter-chuyen-doi-usb-c-6-in-1-ugreen-60384,Adapter chuyển đổi USB C 6 in 1 Ugreen 60384,Adapter chuyển đổi USB C 6 in 1 Ugreen 60384 m...,capsac
3,adapter-sac-3-cong-usb-type-c-iq4-gan-120w-ank...,Sạc 3 cổng Anker A2148,Adapter sạc 3 cổng USB Type C IQ4 GaN 120W Ank...,capsac
4,cap-type-c-1m-xmobile-dr-t10?utm_flashsale=1,Cáp Type C 1m Xmobile DR-T10,"Với cáp Type C 1m Xmobile DR-T10, việc sạc pin...",capsac

In [22]:
miengdan = pd.read_csv('miengdan.csv')
miengdan["category"]="accessory"
miengdan.head()

,id_product,name_product,description,category
0,mieng-dan-kinh-cuong-luc-iphone-16-pro-max-pre...,Miếng dán kính cường lực iPhone 16 Pro Max Pre...,Miếng dán kính cường lực iPhone 16 Pro Max Pre...,accessory
1,mieng-dan-kinh-cuong-luc-iphone-16-premium-jin...,Miếng dán kính cường lực iPhone 16 Premium Jin...,"Được thiết kế với phong cách tối giản, miếng d...",accessory
2,mieng-dan-kinh-cuong-luc-iphone-16-pro-premium...,Miếng dán kính cường lực iPhone 16 Pro Premium...,"Mặc dù có thiết kế đơn giản, nhưng miếng dán k...",accessory
3,mieng-dan-kinh-cuong-luc-iphone-16-plus-premiu...,Miếng dán kính cường lực iPhone 16 Plus Premiu...,Miếng dán kính cường lực iPhone 16 Plus Premiu...,accessory
4,mieng-dan-kinh-cuong-luc-iphone-16-pro-max-jin...,Miếng dán kính cường lực iPhone 16 Pro Max Jin...,Miếng dán kính cường lực iPhone 16 Pro Max Jin...,accessory

In [23]:
oplung = pd.read_csv('oplung.csv')
oplung["category"]="accessory"
oplung.head()

,id_product,name_product,description,category
0,op-lung-iphone-16-pro-max-nhua-cung-vien-deo-b...,Ốp lưng iPhone 16 Pro Max nhựa cứng viền dẻo J...,Ốp lưng iPhone 16 Pro Max nhựa cứng viền dẻo J...,accessory
1,op-lung-iphone-16-pro-max-magsafe-nhua-cung-vi...,Ốp lưng MagSafe iPhone 16 Pro Max nhựa cứng vi...,Ốp lưng MagSafe iPhone 16 Pro Max nhựa cứng vi...,accessory
2,op-lung-iphone-16-pro-magsafe-nhua-cung-vien-d...,Ốp lưng MagSafe iPhone 16 Pro nhựa cứng viền d...,Ốp lưng MagSafe iPhone 16 Pro nhựa cứng viền d...,accessory
3,op-lung-iphone-16-pro-max-magsafe-stand-nhua-c...,Ốp lưng MagSafe iPhone 16 Pro Max nhựa cứng vi...,Ốp lưng MagSafe iPhone 16 Pro Max nhựa cứng vi...,accessory
4,op-lung-iphone-16-pro-max-magsafe-nhua-cung-vi...,Ốp lưng MagSafe iPhone 16 Pro Max nhựa cứng vi...,Sở hữu ốp lưng nhựa cứng viền dẻo Platinium II...,accessory

In [24]:
phukienlaptop = pd.read_csv('phukienlaptop.csv')
phukienlaptop["category"]="accessory"
phukienlaptop.head()

,id_product,name_product,description,category
0,adapter-chuyen-doi-usb-c-6-in-1-ugreen-60384,Adapter chuyển đổi USB C 6 in 1 Ugreen 60384,Adapter chuyển đổi USB C 6 in 1 Ugreen 60384 m...,accessory
1,adapter-chuyen-doi-type-c-4-in-1-xmobile-ds606h,Adapter chuyển đổi Type C 4 in 1 Xmobile DS606H,Adapter chuyển đổi Type C 4 in 1 Xmobile DS606...,accessory
2,adapter-chuyen-doi-type-c-4-in-1-xmobile-ds122f,Adapter chuyển đổi Type C 4 in 1 Xmobile DS122F,"Thiết kế nhỏ gọn, dễ mang theo bên người Adapt...",accessory
3,adapter-chuyen-doi-usb-type-c-4-in-1-hyperdriv...,Adapter chuyển đổi USB Type C 4 in 1 HyperDriv...,Adapter chuyển đổi USB Type C 4 in 1 HyperDriv...,accessory
4,cap-chuyen-doi-type-c-sang-35mm-apple-mu7e2-trang,Cáp chuyển đổi Type C - 3.5mm Apple MU7E2,Cáp chuyển đổi Type-C sang 3.5mm Apple MU7E2 T...,accessory

In [25]:
sacdp = pd.read_csv('sacdp.csv')
sacdp["category"]="accessory"
sacdp.head()

,id_product,name_product,description,category
0,pin-sac-du-phong-polymer-20000mah-type-c-pd-qc...,Xmobile 45W MH803 kèm Cáp Lightning và Type C,"Trong cuộc sống hiện đại, việc sở hữu một sạc ...",accessory
1,sac-du-phong-polymer-10000mah-khong-day-magnet...,Ugreen 20W PB206,Pin sạc dự phòng Polymer 10000mAh Không dây Ma...,accessory
2,pin-sac-du-phong-10000mah-type-c-pd-qc-3-0-55w...,Xmobile 55W JP326,Pin sạc dự phòng 10000mAh Type C PD QC 3.0 55W...,accessory
3,pin-sac-du-phong-10000mah-type-c-pd-22-5w-xmob...,Xmobile 22.5W NeoMice GN-82 kèm Cáp Lightning ...,"Trong cuộc sống hiện đại, việc sở hữu một thiế...",accessory
4,pin-sac-du-phong-10000mah-type-c-pd-qc-3-0-33w...,Xiaomi 33W PB1033MI kèm Cáp Type C,Pin sạc dự phòng 10000mAh Type C PD QC 3.0 33W...,accessory

In [26]:
smartwatch = pd.read_csv('smartwatch.csv')
smartwatch["category"]="smartwatch"
smartwatch.head()

,id_product,name_product,description,category
0,huawei-watch-fit-4,Huawei Watch Fit 4 43mm dây silicone,Huawei vừa chính thức trình làng Huawei Watch ...,smartwatch
1,huawei-watch-fit-4-pro,Huawei Watch Fit 4 Pro 44.5mm dây silicone,Huawei tiếp tục khẳng định vị thế trong thị tr...,smartwatch
2,huawei-watch-fit-4-pro-day-nylon,Huawei Watch Fit 4 Pro 44.5mm dây nylon,Huawei tiếp tục khẳng định vị thế tiên phong t...,smartwatch
3,xiaomi-redmi-watch-5,Xiaomi Redmi Watch 5 47.5 mm dây TPU,"Tại sự kiện ra mắt sản phẩm mới, Xiaomi không ...",smartwatch
4,huawei-watch-gt-5-46mm-vien-thep-day-cao-su,Huawei Watch GT 5 46mm viền thép dây cao su,Huawei Watch GT 5 46mm viền thép dây cao su là...,smartwatch

In [27]:
tablet = pd.read_csv('tablet.csv')
tablet["category"]="tablet"
tablet.head()

,id_product,name_product,description,category
0,ipad-11-wifi-128gb,iPad A16 WiFi 128GB,Xem thêm,tablet
1,ipad-air-m3-11-inch-wifi-128gb,iPad Air M3 11 inch WiFi 128GB,Xem thêm,tablet
2,xiaomi-pad-7-8gb-256gb,Xiaomi Pad 7 WiFi 8GB/256GB,"Ra mắt vào tháng 3/2025, Xiaomi Pad 7 256GB nh...",tablet
3,oppo-pad-3,OPPO Pad 3 8GB/256GB,"OPPO Pad 3 sở hữu thiết kế mỏng nhẹ, màn hình ...",tablet
4,samsung-galaxy-tab-s10-fe,Samsung Galaxy Tab S10 FE WiFi 8GB/128GB,Samsung Galaxy Tab S10 FE là máy tính bảng cao...,tablet

In [28]:
tainghe = pd.read_csv('tainghe.csv')
tainghe["category"]="audio"
tainghe.head()

,id_product,name_product,description,category
0,tai-nghe-bluetooth-truyen-am-thanh-qua-khong-k...,Tai nghe Havit Hakii Light,Nếu bạn đang tìm kiếm một chiếc tai nghe phù h...,audio
1,tai-nghe-bluetooth-true-wireless-oppo-enco-bud...,Tai nghe TWS OPPO ENCO Buds 3 Pro ETEK1,OPPO ENCO Buds 3 Pro ETEK1 là một lựa chọn tai...,audio
2,tai-nghe-bluetooth-tws-xiaomi-redmi-buds-6-lite,Tai nghe TWS Xiaomi Redmi Buds 6 Lite,Tai nghe Bluetooth TWS Xiaomi Redmi Buds 6 Lit...,audio
3,tai-nghe-tws-jbl-wave-beam-2,Tai nghe TWS JBL Wave Beam 2,Bước vào thế giới âm thanh đỉnh cao với tai ng...,audio
4,tai-nghe-bluetooth-truyen-xuong-shokz-openswim...,Tai nghe truyền xương Shokz OPENSWIM PRO S710,Tai nghe Bluetooth truyền xương Shokz OpenSwim...,audio

In [29]:
tuidung = pd.read_csv('tuidung.csv')
tuidung["category"]="accessory"
tuidung.head()

,id_product,name_product,description,category
0,tui-dung-airpods-pro-2-nhua-pc-tpu-uniq-clyde-...,Túi đựng AirPods Pro 2 nhựa PC TPU UniQ Clyde ...,Đặc điểm nổi bật Túi đựng Clyde Lock Case được...,accessory
1,tui-dung-airpods-4-silicone-pc-kem-moc-uniq-ne...,Túi đựng AirPods 4 Silicone PC kèm móc UNIQ Ne...,Đặc điểm nổi bật Túi đựng AirPods 4 Silicone P...,accessory
2,tui-dung-airpods-4-silicone-pc-uniq-lino-hybri...,Túi đựng AirPods 4 Silicone PC UNIQ Lino Hybri...,Đặc điểm nổi bật Túi đựng AirPods 4 Silicone P...,accessory
3,pro-nhua-deo-tpu-nap18,Túi đựng Airpods Pro Nhựa dẻo TPU kèm móc JM N...,"Đặc điểm nổi bật Thiết kế đẹp mắt, 3 màu lựa c...",accessory
4,tui-dung-airpods-pro-2-da-uniq-terra-genuine-nau,Túi đựng AirPods Pro 2 Da UNIQ TERRA GENUINE Nâu,Đặc điểm nổi bật Vỏ ngoài túi đựng AirPods Pro...,accessory

In [30]:
df = pd.concat([laptop, mobile, camera, capsac, miengdan, oplung, phukienlaptop, sacdp, smartwatch, tablet, tainghe, tuidung], axis=0 , ignore_index=True)
df.shape

(2850, 4)

In [31]:
df.head()

,id_product,name_product,description,category
0,asus-vivobook-go-15-e1504fa-r5-nj776w,Asus Vivobook Go 15 E1504FA R5 7520U (NJ776W),Laptop Asus Vivobook Go 15 E1504FA R5 7520U (N...,laptop
1,hp-15-fd0234tu-i5-9q969pa,HP 15 fd0234TU i5 1334U (9Q969PA),Tích hợp tuyệt vời với đa dạng chế độ làm việc...,laptop
2,dell-inspiron-15-3520-i5-n5i5057w1,Dell Inspiron 15 3520 i5 1235U (N5I5057W1),Laptop Dell Inspiron 15 3520 i5 1235U (N5I5057...,laptop
3,lenovo-ideapad-slim-3-15irh10-i5-83k1000hvn,Lenovo IdeaPad Slim 3 15IRH10 i5 13420H (83K10...,Laptop Lenovo IdeaPad Slim 3 15IRH10 i5 13420H...,laptop
4,macbook-air-13-inch-m4-16gb-256gb,MacBook Air 13 inch M4 16GB/256GB,"Không làm người dùng thất vọng, Apple đã cho r...",laptop

In [32]:
df.to_csv('products.csv', index=False)

In [33]:
df_1 = pd.read_csv('products.csv')
df_1.describe()

,id_product,name_product,description,category
count,2850,2850,2850,2850
unique,2694,2646,1863,8
top,tai-nghe-bluetooth-chup-tai-baseus-bass-35-max,Tai nghe Chụp Tai Havit H667BT,Không có mô tả,accessory
freq,3,3,826,1185

In [34]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2850 entries, 0 to 2849
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_product    2850 non-null   object
 1   name_product  2850 non-null   object
 2   description   2850 non-null   object
 3   category      2850 non-null   object
dtypes: object(4)
memory usage: 89.2+ KB

In [18]:
import pandas as pd
df = pd.read_csv('../data/product/final_products.csv')
df.head()

,id_product,name_product,description,category,img
0,asus-vivobook-go-15-e1504fa-r5-nj776w,Asus Vivobook Go 15 E1504FA R5 7520U (NJ776W),Laptop Asus Vivobook Go 15 E1504FA R5 7520U (N...,laptop,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
1,hp-15-fd0234tu-i5-9q969pa,HP 15 fd0234TU i5 1334U (9Q969PA),Tích hợp tuyệt vời với đa dạng chế độ làm việc...,laptop,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
2,dell-inspiron-15-3520-i5-n5i5057w1,Dell Inspiron 15 3520 i5 1235U (N5I5057W1),Laptop Dell Inspiron 15 3520 i5 1235U (N5I5057...,laptop,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
3,lenovo-ideapad-slim-3-15irh10-i5-83k1000hvn,Lenovo IdeaPad Slim 3 15IRH10 i5 13420H (83K10...,Laptop Lenovo IdeaPad Slim 3 15IRH10 i5 13420H...,laptop,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
4,macbook-air-13-inch-m4-16gb-256gb,MacBook Air 13 inch M4 16GB/256GB,"Không làm người dùng thất vọng, Apple đã cho r...",laptop,https://cdn.tgdd.vn/Products/Images/44/335362/...

In [ ]:
dongho = pd.read_csv('../data/product/dongho.csv')
dongho["category"]="watch"
dongho.head()

,id_product,name_product,description,img,category
0,citizen-bi5120-51l-nam,CITIZEN 40 mm Nam BI5120-51L,Đồng hồ Citizen 40mm Nam BI5120-51L là một lựa...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...,watch
1,citizen-bi5120-51x-nam?utm_flashsale=1,CITIZEN 40 mm Nam BI5120-51X,"Dây bạc thanh lịch, màu mặt xanh lá bắt mắt là...",https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...,watch
2,citizen-el3100-55z-nu,CITIZEN 31 mm Nữ EL3100-55Z,Không có mô tả,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...,watch
3,citizen-nj0151-88l-nam,CITIZEN Tsuyosa 40 mm Nam NJ0151-88L,• Citizen Tsuyosa 40mm NJ0151-88L là sự kết hợ...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...,watch
4,orient-ra-as0105s30b-nam,ORIENT Vietnam Special Edition 41.5 mm Nam RA-...,• Là phiên bản dành riêng cho thị trường Việt ...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...,watch

In [ ]:
df1 = pd.concat([df,dongho], axis=0 , ignore_index=True)
print(df1.shape)

(5876, 5)

In [23]:
df1.to_csv('../data/product/products.csv', index=False)

In [25]:
# Import thư viện
import pandas as pd

# Đọc file all_reviews.csv
df = pd.read_csv('../data/all_reviews.csv')

# Đếm số rating mỗi sản phẩm
ratings_per_product = df.groupby('id_product').size()

# Chuyển thành DataFrame
df_product_ratings = ratings_per_product.reset_index()
df_product_ratings.columns = ['id_product', 'ratings_count']

# Lọc sản phẩm có từ 10 rating trở lên
min_ratings = 5
filtered_products = df_product_ratings[df_product_ratings['ratings_count'] >= min_ratings]

# Hiển thị kết quả
print(f"Số sản phẩm có từ {min_ratings} rating trở lên: {len(filtered_products)}")
print("\nThống kê số rating mỗi sản phẩm (sau khi lọc):")
print(filtered_products['ratings_count'].describe())
print("\nDanh sách sản phẩm có từ 10 rating trở lên:")
print(filtered_products)

# (Tùy chọn) Thêm tên sản phẩm từ df
filtered_products_with_names = filtered_products.merge(
    df[['id_product', 'name_product']].drop_duplicates(),
    on='id_product',
    how='left'
)
print("\nDanh sách sản phẩm có tên và số rating:")
print(filtered_products_with_names[['id_product', 'name_product', 'ratings_count']])

Số sản phẩm có từ 5 rating trở lên: 1591

Thống kê số rating mỗi sản phẩm (sau khi lọc):
count    1591.000000
mean       24.129478
std        45.693533
min         5.000000
25%         7.000000
50%        11.000000
75%        20.000000
max       681.000000
Name: ratings_count, dtype: float64

Danh sách sản phẩm có từ 10 rating trở lên:
                                        id_product  ratings_count
0                   1-2-nhua-deo-silicone-ck-ap002             10
1     10000mah-lightning-xmobile-lj-jp90s-nhom-xam            210
2        acer-aspire-3-a314-42p-r3b3-r7-nxksfsv001              7
3         acer-aspire-3-a315-59-5283-i5-nxk6tsv00b             10
4       acer-aspire-5-a515-58gm-51lb-i5-nxkq4sv002             29
...                                            ...            ...
2497                              xiaomi-watch-s-3             76
2498                                  zenbos-k-200             24
2499                                  zenbos-k-360             23
2500                                 zenbos-mz-201             39
2501                                 zenbos-mz-202             28

[1591 rows x 2 columns]

Danh sách sản phẩm có tên và số rating:
                                        id_product  \
0                   1-2-nhua-deo-silicone-ck-ap002
1     10000mah-lightning-xmobile-lj-jp90s-nhom-xam
2        acer-aspire-3-a314-42p-r3b3-r7-nxksfsv001
3         acer-aspire-3-a315-59-5283-i5-nxk6tsv00b
4       acer-aspire-5-a515-58gm-51lb-i5-nxkq4sv002
...                                            ...
1586                              xiaomi-watch-s-3
1587                                  zenbos-k-200
1588                                  zenbos-k-360
1589                                 zenbos-mz-201
1590                                 zenbos-mz-202

                                           name_product  ratings_count
0        Túi đựng Airpods 1 & 2 Nhựa dẻo OSMIA CK-AP002             10
1                                  Xmobile 10W LJ JP90S            210
2     Acer Aspire 3 A314 42P R3B3 R7 5700U (NX.KSFSV...              7
3     Acer Aspire 3 A315 59 5283 i5 1235U (NX.K6TSV....             10
4     Acer Gaming Aspire 5 A515 58GM 51LB i5 13420H ...             29
...                                                 ...            ...
1586                  Xiaomi Watch S3 47mm dây silicone             76
1587                               Loa kéo Zenbos K-200             24
1588                               Loa kéo Zenbos K-360             23
1589                      Micro không dây Zenbos MZ-201             39
1590                      Micro không dây Zenbos MZ-202             28

[1591 rows x 3 columns]

In [27]:
# Import thư viện
import pandas as pd

# Đọc file all_reviews.csv
df = pd.read_csv('../data/all_reviews.csv')

# Kiểm tra cấu trúc dữ liệu
print("Thống kê mô tả của DataFrame:")
print(df.describe(include='all'))

# Nhóm theo name_product và đếm số id_product duy nhất
product_counts = df.groupby('name_product')['id_product'].nunique().reset_index()
product_counts.columns = ['name_product', 'id_count']

# Lọc các name_product có hơn 1 id_product (tức là trùng tên nhưng khác ID)
duplicate_names = product_counts[product_counts['id_count'] > 1]

# Đếm số sản phẩm trùng tên nhưng khác ID
num_duplicate_products = len(duplicate_names)
print(f"\nSố sản phẩm có tên trùng nhưng khác id_product: {num_duplicate_products}")

# Hiển thị danh sách chi tiết
print("\nDanh sách các sản phẩm trùng tên nhưng khác id_product:")
print(duplicate_names)

# (Tùy chọn) Hiển thị chi tiết các id_product cho từng name_product trùng
print("\nChi tiết id_product cho các tên sản phẩm trùng:")
for name in duplicate_names['name_product']:
    ids = df[df['name_product'] == name]['id_product'].unique()
    print(f"Tên sản phẩm: {name}, Các id_product: {ids}")

# (Tùy chọn) Thống kê số lần xuất hiện của các tên sản phẩm trùng
print("\nThống kê số lần xuất hiện của các tên sản phẩm trùng:")
duplicate_details = df[df['name_product'].isin(duplicate_names['name_product'])][['name_product', 'id_product']].drop_duplicates()
print(duplicate_details.groupby('name_product').size().reset_index(name='count'))

Thống kê mô tả của DataFrame:
                                              id_product     name_product  \
count                                              40232            40232
unique                                              2502             2490
top     pin-sac-du-phong-polymer-10000mah-12w-ava-ds609a  AVA+ 12W DS609A
freq                                                 681              681
mean                                                 NaN              NaN
std                                                  NaN              NaN
min                                                  NaN              NaN
25%                                                  NaN              NaN
50%                                                  NaN              NaN
75%                                                  NaN              NaN
max                                                  NaN              NaN

       username        rating
count     40178  40232.000000
unique    21147           NaN
top        Linh           NaN
freq        150           NaN
mean        NaN      4.146202
std         NaN      1.193680
min         NaN      1.000000
25%         NaN      4.000000
50%         NaN      5.000000
75%         NaN      5.000000
max         NaN      5.000000

Số sản phẩm có tên trùng nhưng khác id_product: 12

Danh sách các sản phẩm trùng tên nhưng khác id_product:
                                           name_product  id_count
123          Bao da Galaxy A34 Smart Clear View Samsung         2
753                        Dây da MVW mặt 44mm RZ31-00A         2
1241                     Kidcare S6 41.5mm dây silicone         2
1370        MSI Gaming GF63 Thin 12VE i5 12450H (460VN)         2
2110                 Tai nghe TWS Gaming Asus Rog Cetra         2
2332  Ốp lưng Galaxy S22 Ultra Nhựa dẻo TPU ARAREE F...         2
2335        Ốp lưng Galaxy S23 Nhựa dẻo ARAREE FLEXIELD         2
2362  Ốp lưng MagSafe iPhone 15 Pro Max Silicone UNI...         2
2380  Ốp lưng Magsafe iPhone 15 Pro Max Nhựa dẻo TPU...         2
2458  Ốp lưng iPhone 14 Nhựa cứng viền dẻo UNIQ LIFE...         2
2475  Ốp lưng iPhone 14 Pro Nhựa cứng viền dẻo Switc...         2
2476  Ốp lưng iPhone 14 Pro Nhựa cứng viền dẻo UNIQ ...         2

Chi tiết id_product cho các tên sản phẩm trùng:
Tên sản phẩm: Bao da Galaxy A34 Smart Clear View Samsung, Các id_product: ['bao-da-galaxy-a34-samsung-smart-clear-view'
 'bao-da-galaxy-a34-samsung-smart-clear-view-chinh-hang']
Tên sản phẩm: Dây da MVW mặt 44mm RZ31-00A, Các id_product: ['day-rz31-00a-da-nau-cam' 'day-rz31-00a-da-xanh-ngoc']
Tên sản phẩm: Kidcare S6 41.5mm dây silicone, Các id_product: ['kidcare-s6-day-silicone-xanh?utm_flashsale=1'
 'kidcare-s6-day-silicone?utm_flashsale=1']
Tên sản phẩm: MSI Gaming GF63 Thin 12VE i5 12450H (460VN), Các id_product: ['msi-gf63-thin-12ve-i5-460vn' 'msi-gaming-gf63-thin-12ve-i5-460vn']
Tên sản phẩm: Tai nghe TWS Gaming Asus Rog Cetra, Các id_product: ['tai-nghe-bluetooth-true-wireless-gaming-asus-rog-cetra-trang'
 'tai-nghe-bluetooth-true-wireless-gaming-asus-rog-cetra']
Tên sản phẩm: Ốp lưng Galaxy S22 Ultra Nhựa dẻo TPU ARAREE FLEXIELD, Các id_product: ['op-lung-galaxy-s22-ultra-nhua-deo-tpu-araree-flexield-den-chinh-hang'
 'op-lung-galaxy-s22-ultra-nhua-deo-tpu-araree-flexield-trong']
Tên sản phẩm: Ốp lưng Galaxy S23 Nhựa dẻo ARAREE FLEXIELD, Các id_product: ['op-lung-galaxy-s23-nhua-deo-araree-flexield-trong'
 'op-lung-galaxy-s23-5g-flexield-nhua-deo-tpu-araree-den-trong']
Tên sản phẩm: Ốp lưng MagSafe iPhone 15 Pro Max Silicone UNIQ HYBRID MAGCLICK CHARGING LINO HUE Liquid, Các id_product: ['op-magsafe-iphone-15-pro-max-silicone-uniq-hybrid-lino-hue-liquid-blue'
 'op-magsafe-iphone-15-pro-max-silicone-uniq-hybrid-lino-hue-liquid-grey']
Tên sản phẩm: Ốp lưng Magsafe iPhone 15 Pro Max Nhựa dẻo TPU LAUT HUEX PROTECT, Các id_product: ['op-lung-magsafe-iphone-15-pro-max-nhua-deo-tpu-laut-huex-protect-dark-blue'
 'op-lung-magsafe-iphone-15-pro-max-nhua-deo-tpu-laut-huex-protect-grey']
Tên sản phẩm: Ốp lưng iPhone 14 Nhựa cứng viền dẻo UNIQ LIFEPRO XTREME, Các id_product: ['op-lung-iphone-14-nhua-cung-vien-deo-uniq-iridescent-lifepro-xtreme'
 'op-lung-iphone-14-nhua-cung-vien-deo-uniq-tinsel-lucent-lifepro-xtreme']
Tên sản phẩm: Ốp lưng iPhone 14 Pro Nhựa cứng viền dẻo SwitchEasy Artist, Các id_product: ['op-lung-iphone-14-pro-nhua-cung-vien-deo-switcheasy-sakura-artist'
 'op-lung-iphone-14-pro-nhua-cung-vien-deo-switcheasy-asanoha-artist']
Tên sản phẩm: Ốp lưng iPhone 14 Pro Nhựa cứng viền dẻo UNIQ COEHL, Các id_product: ['op-lung-iphone-14-pro-nhua-cung-vien-deo-uniq-spring-pink-coehl'
 'op-lung-iphone-14-pro-nhua-cung-vien-deo-uniq-stardust-coehl']

Thống kê số lần xuất hiện của các tên sản phẩm trùng:
                                         name_product  count
0          Bao da Galaxy A34 Smart Clear View Samsung      2
1                        Dây da MVW mặt 44mm RZ31-00A      2
2                      Kidcare S6 41.5mm dây silicone      2
3         MSI Gaming GF63 Thin 12VE i5 12450H (460VN)      2
4                  Tai nghe TWS Gaming Asus Rog Cetra      2
5   Ốp lưng Galaxy S22 Ultra Nhựa dẻo TPU ARAREE F...      2
6         Ốp lưng Galaxy S23 Nhựa dẻo ARAREE FLEXIELD      2
7   Ốp lưng MagSafe iPhone 15 Pro Max Silicone UNI...      2
8   Ốp lưng Magsafe iPhone 15 Pro Max Nhựa dẻo TPU...      2
9   Ốp lưng iPhone 14 Nhựa cứng viền dẻo UNIQ LIFE...      2
10  Ốp lưng iPhone 14 Pro Nhựa cứng viền dẻo Switc...      2
11  Ốp lưng iPhone 14 Pro Nhựa cứng viền dẻo UNIQ ...      2