In [1]:
import pandas as pd
laptop = pd.read_csv('laptops_img.csv')
laptop.head()

,id_product,name_product,img
0,asus-vivobook-go-15-e1504fa-r5-nj776w,Asus Vivobook Go 15 E1504FA R5 7520U (NJ776W),https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
1,hp-15-fd0234tu-i5-9q969pa,HP 15 fd0234TU i5 1334U (9Q969PA),https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
2,dell-inspiron-15-3520-i5-n5i5057w1,Dell Inspiron 15 3520 i5 1235U (N5I5057W1),https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
3,lenovo-ideapad-slim-3-15irh10-i5-83k1000hvn,Lenovo IdeaPad Slim 3 15IRH10 i5 13420H (83K10...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
4,macbook-air-13-inch-m4-16gb-256gb,MacBook Air 13 inch M4 16GB/256GB,https://cdn.tgdd.vn/Products/Images/44/335362/...

In [2]:
mobile = pd.read_csv('mobile_img.csv')
mobile.head()

,id_product,name_product,img
0,vivo-y19s-pro-8gb,vivo Y19s Pro 8GB/128GB,https://cdn.tgdd.vn/Products/Images/42/338918/...
1,honor-400-5g-12gb-256gb-den,HONOR 400 5G 12GB/256GB Đen,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
2,oppo-a5x-4gb-64gb,OPPO A5x 4GB/64GB,https://cdn.tgdd.vn/Products/Images/42/337846/...
3,iphone-16-pro-max,iPhone 16 Pro Max 256GB,https://cdn.tgdd.vn/Products/Images/42/329149/...
4,iphone-16-pro,iPhone 16 Pro 128GB,https://cdn.tgdd.vn/Products/Images/42/329143/...

In [3]:
camera = pd.read_csv('camera_img.csv')
camera.head()

,id_product,name_product,img
0,camera-ip-360-do-2mp-tp-link-tapo-c200c,Camera IP 360 Độ 2MP TP-Link Tapo C200C,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
1,camera-ip-360-do-3mp-imou-ta32cp-l-trang,Camera IP 360 Độ 3MP IMOU TA32CP-L,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
2,camera-ip-360-do-1080p-ezviz-c6n-trang,Camera IP 360 Độ 2MP Ezviz C6N,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
3,camera-ip-360-do-2mp-tiandy-tc-h322n,Camera IP 360 Độ 2MP TIANDY TC-H322N,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
4,camera-ip-360-do-3mp-ezviz-ty1,Camera IP 360 Độ 3MP EZVIZ TY1,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...

In [4]:
capsac = pd.read_csv('capsac_img.csv')
capsac.head()

,id_product,name_product,img
0,cap-type-c-type-c-2m-xmobile-dr-t11?utm_flashs...,Cáp Type C - Type C 2m Xmobile DR-T11,https://cdn.tgdd.vn/Products/Images/58/328421/...
1,sac-xe-hoi-type-c-pd-30w-baseus-tiny-star-mini...,Sạc xe hơi Baseus VCHXXC,https://cdn.tgdd.vn/Products/Images/9499/32814...
2,cap-type-c-type-c-0-9m-anker-322-a81f5,Cáp Type C - Type C 0.9m Anker 322 A81F5,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
3,adapter-chuyen-doi-usb-c-6-in-1-ugreen-60384,Adapter chuyển đổi USB C 6 in 1 Ugreen 60384,https://cdn.tgdd.vn/Products/Images/12979/3275...
4,adapter-sac-3-cong-usb-type-c-iq4-gan-120w-ank...,Sạc 3 cổng Anker A2148,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...

In [5]:
miengdan = pd.read_csv('miengdan_img.csv')
miengdan.head()

,id_product,name_product,img
0,mieng-dan-kinh-cuong-luc-iphone-16-pro-max-pre...,Miếng dán kính cường lực iPhone 16 Pro Max Pre...,https://cdn.tgdd.vn/Products/Images/1363/32993...
1,mieng-dan-kinh-cuong-luc-iphone-16-premium-jin...,Miếng dán kính cường lực iPhone 16 Premium Jin...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
2,mieng-dan-kinh-cuong-luc-iphone-16-pro-premium...,Miếng dán kính cường lực iPhone 16 Pro Premium...,https://cdn.tgdd.vn/Products/Images/1363/32993...
3,mieng-dan-kinh-cuong-luc-iphone-16-plus-premiu...,Miếng dán kính cường lực iPhone 16 Plus Premiu...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
4,mieng-dan-kinh-cuong-luc-iphone-16-pro-max-jin...,Miếng dán kính cường lực iPhone 16 Pro Max Jin...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...

In [7]:
oplung = pd.read_csv('oplung_img.csv')
oplung.head()

,id_product,name_product,img
0,op-lung-iphone-16-pro-max-nhua-cung-vien-deo-b...,Ốp lưng iPhone 16 Pro Max nhựa cứng viền dẻo J...,https://cdn.tgdd.vn/Products/Images/60/329711/...
1,op-lung-iphone-16-pro-max-magsafe-nhua-cung-vi...,Ốp lưng MagSafe iPhone 16 Pro Max nhựa cứng vi...,https://cdn.tgdd.vn/Products/Images/60/329712/...
2,op-lung-iphone-16-pro-magsafe-nhua-cung-vien-d...,Ốp lưng MagSafe iPhone 16 Pro nhựa cứng viền d...,https://cdn.tgdd.vn/Products/Images/60/329716/...
3,op-lung-iphone-16-pro-max-magsafe-stand-nhua-c...,Ốp lưng MagSafe iPhone 16 Pro Max nhựa cứng vi...,https://cdn.tgdd.vn/Products/Images/60/329714/...
4,op-lung-iphone-16-pro-max-magsafe-nhua-cung-vi...,Ốp lưng MagSafe iPhone 16 Pro Max nhựa cứng vi...,https://cdn.tgdd.vn/Products/Images/60/329713/...

In [8]:
phukienlaptop = pd.read_csv('phukienlaptop_img.csv')
phukienlaptop.head()

,id_product,name_product,img
0,adapter-chuyen-doi-usb-c-6-in-1-ugreen-60384,Adapter chuyển đổi USB C 6 in 1 Ugreen 60384,https://cdn.tgdd.vn/Products/Images/12979/3275...
1,adapter-chuyen-doi-type-c-4-in-1-xmobile-ds606h,Adapter chuyển đổi Type C 4 in 1 Xmobile DS606H,https://cdn.tgdd.vn/Products/Images/12979/3268...
2,adapter-chuyen-doi-type-c-4-in-1-xmobile-ds122f,Adapter chuyển đổi Type C 4 in 1 Xmobile DS122F,https://cdn.tgdd.vn/Products/Images/12979/2531...
3,adapter-chuyen-doi-usb-type-c-4-in-1-hyperdriv...,Adapter chuyển đổi USB Type C 4 in 1 HyperDriv...,https://cdn.tgdd.vn/Products/Images/12979/3106...
4,cap-chuyen-doi-type-c-sang-35mm-apple-mu7e2-trang,Cáp chuyển đổi Type C - 3.5mm Apple MU7E2,https://cdn.tgdd.vn/Products/Images/12979/2037...

In [9]:
sacdp = pd.read_csv('sacdp_img.csv')
sacdp.head()

,id_product,name_product,img
0,pin-sac-du-phong-polymer-20000mah-type-c-pd-qc...,Xmobile 45W MH803 kèm Cáp Lightning và Type C,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
1,sac-du-phong-polymer-10000mah-khong-day-magnet...,Ugreen 20W PB206,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
2,pin-sac-du-phong-10000mah-type-c-pd-qc-3-0-55w...,Xmobile 55W JP326,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
3,pin-sac-du-phong-10000mah-type-c-pd-22-5w-xmob...,Xmobile 22.5W NeoMice GN-82 kèm Cáp Lightning ...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
4,pin-sac-du-phong-10000mah-type-c-pd-qc-3-0-33w...,Xiaomi 33W PB1033MI kèm Cáp Type C,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...

In [10]:
smartwatch = pd.read_csv('smartwatch_img.csv')
smartwatch.head()

,id_product,name_product,img
0,huawei-watch-fit-4,Huawei Watch Fit 4 43mm dây silicone,https://cdn.tgdd.vn/Products/Images/7077/33443...
1,huawei-watch-fit-4-pro,Huawei Watch Fit 4 Pro 44.5mm dây silicone,https://cdn.tgdd.vn/Products/Images/7077/33694...
2,huawei-watch-fit-4-pro-day-nylon,Huawei Watch Fit 4 Pro 44.5mm dây nylon,https://cdn.tgdd.vn/Products/Images/7077/33816...
3,xiaomi-redmi-watch-5,Xiaomi Redmi Watch 5 47.5 mm dây TPU,https://cdn.tgdd.vn/Products/Images/7077/33206...
4,huawei-watch-gt-5-46mm-vien-thep-day-cao-su,Huawei Watch GT 5 46mm viền thép dây cao su,https://cdn.tgdd.vn/Products/Images/7077/33017...

In [11]:
tablet = pd.read_csv('tablet_img.csv')
tablet.head()

,id_product,name_product,img
0,ipad-11-wifi-128gb,iPad A16 WiFi 128GB,https://cdn.tgdd.vn/Products/Images/522/335308...
1,ipad-air-m3-11-inch-wifi-128gb,iPad Air M3 11 inch WiFi 128GB,https://cdn.tgdd.vn/Products/Images/522/335267...
2,xiaomi-pad-7-8gb-256gb,Xiaomi Pad 7 WiFi 8GB/256GB,https://cdn.tgdd.vn/Products/Images/522/334530...
3,oppo-pad-3,OPPO Pad 3 8GB/256GB,https://cdn.tgdd.vn/Products/Images/522/333917...
4,samsung-galaxy-tab-s10-fe,Samsung Galaxy Tab S10 FE WiFi 8GB/128GB,https://cdn.tgdd.vn/Products/Images/522/336737...

In [12]:
tainghe = pd.read_csv('tainghe_img.csv')
tainghe.head()

,id_product,name_product,img
0,tai-nghe-bluetooth-truyen-am-thanh-qua-khong-k...,Tai nghe Havit Hakii Light,https://cdn.tgdd.vn/Products/Images/54/327984/...
1,tai-nghe-bluetooth-true-wireless-oppo-enco-bud...,Tai nghe TWS OPPO ENCO Buds 3 Pro ETEK1,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
2,tai-nghe-bluetooth-tws-xiaomi-redmi-buds-6-lite,Tai nghe TWS Xiaomi Redmi Buds 6 Lite,https://cdn.tgdd.vn/Products/Images/54/328697/...
3,tai-nghe-tws-jbl-wave-beam-2,Tai nghe TWS JBL Wave Beam 2,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
4,tai-nghe-bluetooth-truyen-xuong-shokz-openswim...,Tai nghe truyền xương Shokz OPENSWIM PRO S710,https://cdn.tgdd.vn/Products/Images/54/328282/...

In [13]:
tuidung = pd.read_csv('tuidung_img.csv')
tuidung.head()

,id_product,name_product,img
0,tui-dung-airpods-pro-2-nhua-pc-tpu-uniq-clyde-...,Túi đựng AirPods Pro 2 nhựa PC TPU UniQ Clyde ...,https://cdn.tgdd.vn/Products/Images/7925/32864...
1,tui-dung-airpods-4-silicone-pc-kem-moc-uniq-ne...,Túi đựng AirPods 4 Silicone PC kèm móc UNIQ Ne...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
2,tui-dung-airpods-4-silicone-pc-uniq-lino-hybri...,Túi đựng AirPods 4 Silicone PC UNIQ Lino Hybri...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
3,pro-nhua-deo-tpu-nap18,Túi đựng Airpods Pro Nhựa dẻo TPU kèm móc JM N...,https://cdn.tgdd.vn/Products/Images/7925/23336...
4,tui-dung-airpods-pro-2-da-uniq-terra-genuine-nau,Túi đựng AirPods Pro 2 Da UNIQ TERRA GENUINE Nâu,https://cdn.tgdd.vn/Products/Images/7925/30793...

In [ ]:
df = pd.concat([laptop, mobile, camera, capsac, miengdan, oplung, phukienlaptop, sacdp, smartwatch, tablet, tainghe, tuidung], axis=0 , ignore_index=True)

,id_product,name_product,img
0,asus-vivobook-go-15-e1504fa-r5-nj776w,Asus Vivobook Go 15 E1504FA R5 7520U (NJ776W),https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
1,hp-15-fd0234tu-i5-9q969pa,HP 15 fd0234TU i5 1334U (9Q969PA),https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
2,dell-inspiron-15-3520-i5-n5i5057w1,Dell Inspiron 15 3520 i5 1235U (N5I5057W1),https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
3,lenovo-ideapad-slim-3-15irh10-i5-83k1000hvn,Lenovo IdeaPad Slim 3 15IRH10 i5 13420H (83K10...,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
4,macbook-air-13-inch-m4-16gb-256gb,MacBook Air 13 inch M4 16GB/256GB,https://cdn.tgdd.vn/Products/Images/44/335362/...

In [16]:
df.shape

(2840, 3)

In [17]:
df.to_csv('products_img.csv', index=False)

In [18]:
df_1 = pd.read_csv('products_img.csv')
df_1.describe()

,id_product,name_product,img
count,2840,2840,2840
unique,2690,2642,2690
top,tai-nghe-bluetooth-chup-tai-logitech-zone-300,Tai nghe Chụp Tai Havit H667BT,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products...
freq,3,3,3

In [19]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2840 entries, 0 to 2839
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_product    2840 non-null   object
 1   name_product  2840 non-null   object
 2   img           2840 non-null   object
dtypes: object(3)
memory usage: 66.7+ KB